# Generated by Django 2.2.1 on 2019-06-25 14:27

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to=courses.models.content_file_name),
            preserve_default=False,
        ),
    ]
