# Generated by Django 2.2.1 on 2019-06-26 10:40

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='/media/ml.jpg', upload_to=courses.models.content_file_name),
        ),
    ]
