# Generated by Django 2.2.1 on 2019-06-26 10:41

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190626_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='/media/defaultImg.jpg', upload_to=courses.models.content_file_name),
        ),
    ]
