# Generated by Django 2.2.1 on 2019-06-26 11:14

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190626_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=courses.models.content_file_name),
        ),
    ]
